### ISSUE TITLE
Afbeeldingen uploaden

### ISSUE THREAD

**Issue by leonvsc** [leonvsc/Premaz#23]
De administrator moet de mogelijkheid hebben om afbeeldingen te uploaden naar de website.

Dit kan bijvoorbeeld een productafbeelding zijn.

**Comment by leonvsc** [comment]
Voor de afbeeldingen gaan we in het admin panel een pagina maken met een file upload. Deze afbeeldingen worden geupload naar een map. In de PHP bestanden kunnen we de geuploade afbeeldingen gebruiken.

**Comment by NielsWarnaar** [comment]
Het uploaden van een afbeelding is nu mogelijk. De functie moet nog "opgeschoond" worden en moet toegevoegd worden aan de functies van de adminpagina.
