### ISSUE TITLE
Contactformulier

### ISSUE THREAD

**Issue by leonvsc** [leonvsc/Premaz#24]
Er moet een contactformulier komen waar de bezoeker van de webshop ons kan contacteren. Het formulier moet de invoervelden controleren of er iets is ingevuld en of dit juist is.

Deze data kunnen we eventueel ophalen in het administrator gedeelte zodat medewerkers hier terug op kunnen reageren.

**Comment by leonvsc** [comment]
Onder klantenservice een pagina aanmaken met contactformulier.

**Comment by leonvsc** [comment]
PR #63 gemaakt met een simpele link naar het oude contactformulier.

Ik hoor graag of we dat zo willen houden of dat we een nieuwe willen met een nieuwe layout @NielsWarnaar @Strivem1

**Comment by NielsWarnaar** [comment]
@leonvsc mij betreft is het gebruiken van het huidige formulier akkoord

**Comment by leonvsc** [comment]
Check! Dan sluit ik bij deze dit issue.
