### ISSUE TITLE
Producten in de webshop

### ISSUE THREAD

**Issue by leonvsc** [leonvsc/Premaz#26]
Er moeten producten aanwezig zijn in de webshop. Deze producten kunnen bekeken worden door klanten. Ook moeten deze in aantallen besteld kunnen worden door klanten.

Producten zijn gecategoriseerd. Er moet dus een overzicht zijn van producten per categorie.

**Comment by NielsWarnaar** [comment]
De product informatie is nu te zien als er een specifieke SKU is ingevuld. 

To do: 
1. Een overzichtspagina maken waar alle producten van de DB komen te staan
2. De producten op de overzichtspagina klikbaar maken om naar het specifieke product te gaan
3. Het mogelijk maken om het product toe te voegen aan de winkelwagen

Ideeën: 
1. Maak de producten pagina door alle data uit de tabel producten op te halen en hierna via een for() loop elke product los op een plek te zetten
