### ISSUE TITLE
Bestelproces

### ISSUE THREAD

**Issue by leonvsc** [leonvsc/Premaz#36]
Een klant moet een bestelling kunnen plaatsen. Deze moet betaald kunnen worden via mollie.

Een bestelling moet een bestelstatus krijgen. Een klant kan de bestelling inzien in zijn account.

**Comment by leonvsc** [comment]
Mollie gaat niet meer lukken door de tijd. We maken een simpele betaalknop waar de gebruiker op kan klikken om de betaling te bevestigen.

**Comment by NielsWarnaar** [comment]
Voor het bestelproces moet het volgende gedaan worden: 

- [ ] Maak een winkelwagen pagina waar een overzicht staat van de producten in de winkelwagen
- [ ] Toon de totaalprijs op deze pagina
- [ ] Maak een knop op deze pagina om de producten te bestellen
- [ ] Na het klikken op "bestellen" wordt er een order aangemaakt waar deze producten in terecht komen
- [ ] De order wordt hierna getoond op een nieuwe pagina waar ook de adresgegevens getoond worden. Op deze pagina kan je "betalen"
- [ ] Na het betalen krijg je een melding dat de betaling voltooid is
